# Generated by Django 3.2.9 on 2021-12-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_before', models.DateTimeField(null=True)),
                ('not_after', models.DateTimeField(null=True)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('cert_content', models.TextField(null=True)),
                ('issuer', models.CharField(max_length=200, null=True)),
                ('subject', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('cert_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('certs', models.ManyToManyField(related_name='dns_list', to='cert_import.Certificate')),
                ('certs_in_use', models.ManyToManyField(related_name='hosts', to='cert_import.Certificate')),
            ],
        ),
    ]
