# Generated by Django 3.2.9 on 2021-11-30 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_start', models.DateField()),
                ('valid_end', models.DateField()),
                ('cert_id', models.CharField(max_length=50)),
                ('cert_content', models.TextField(null=True)),
                ('ca_chain', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='cert_import.certificate')),
            ],
        ),
        migrations.CreateModel(
            name='DNS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('certs', models.ManyToManyField(related_name='dns', to='cert_import.Certificate')),
            ],
        ),
    ]
