# Generated by Django 3.2.9 on 2021-12-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert_import', '0002_auto_20211201_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='cert',
            new_name='cert_in_use',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='ca_chain',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='extension',
        ),
        migrations.AddField(
            model_name='host',
            name='certs',
            field=models.ManyToManyField(null=True, related_name='dns_list', to='cert_import.Certificate'),
        ),
    ]
